### ISSUE TITLE
Refactor grant_group_role and revoke_group_role to use single command for sqlalchemy.

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-iam-db-authn-groups#17]
Currently, the granting and revoking of role to db users is done through a loop. Want to refactor code so single command will grant role to all users of a list.

**Comment by jackwotherspoon** [comment]
Closed wrong issue as part of PR... oops

**Comment by enocom** [comment]
Closing this as stale.
